services:

  api:
    # container_name: "myapp_api_app"
    restart: always
    build: .
    environment:
      APP_NODE_ENV: ${APP_NODE_ENV:-production}
      TZ: ${TZ:-UTC} # Set timezone (default to UTC)
      APP_FALLBACK_LANG_ALL: ${APP_FALLBACK_LANG_ALL:-en} # Set fallback language (default to en)
      REDIS_HOST: redis # the same for redis. Use redis container name instead of localhost
      REDIS_PORT: 6379
      # POSTGRES_HOST: postgres # localhost doesn't work in docker container, hence you should use postgres container name instead of localhost
      # DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
    command: pnpm run start:dev
    # env_file:
    #     - .env
    ports:
      - '${APP_PORT:-3011}:3000'
    depends_on:
      - postgres
      - redis
    networks:
      - akalin-tech-nestjs-full-auth-api-network

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${TZ:-UTC}
    ports:
      - "${POSTGRES_PORT:-5432}" # Changed host port to avoid conflict with local PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - akalin-tech-nestjs-full-auth-api-network
    # healthcheck:
    #   test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redispassword}
    networks:
      - akalin-tech-nestjs-full-auth-api-network
    restart: always

networks:
  akalin-tech-nestjs-full-auth-api-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
